#!/bin/sh

output="config.h"
logfile="/tmp/clap.log"
date="$(date +%Y%m%d_%H%M%S)"
if [ "$(basename $CC)" = "emcc" ]; then
    #echo "Building a browser version"
    do_browser=1
fi
if [ -n "$OBJDIR" ]; then
    output="$OBJDIR/$output"
fi

: > $output
echo "/* Autogenerated, edit config.sh instead */" >> $output
echo "#ifndef __CLAP_CONFIG_H__" >> $output
echo "#define __CLAP_CONFIG_H__" >> $output
echo "#define CONFIG_LOG_OUTPUT \"$logfile\"" >> $output
echo "#define CONFIG_BUILDDATE \"$date\"" >> $output
if [ -n "$do_browser" ]; then
    echo "#define CONFIG_BROWSER 1" >> $output
    echo "#define CONFIG_GLES 1" >> $output
fi
echo "#endif /* __CLAP_CONFIG_H__ */" >> $output
