# Write the assembly file ${asset_asm} that contains ${asset_cpio} binary
if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    set(SECTION "\"__DATA_CONST\", __const")
    set(SYM_PREFIX "_")
elseif (${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    set(SECTION "\".rodata\"")
    set(SYM_PREFIX "")
endif()

FILE(WRITE  ${asset_asm} ".section ${SECTION}\n")
FILE(APPEND ${asset_asm} ".global ${SYM_PREFIX}clap_asset_cpio_start\n")
FILE(APPEND ${asset_asm} ".balign 16\n")
FILE(APPEND ${asset_asm} "${SYM_PREFIX}clap_asset_cpio_start:\n")
if (NOT empty)
    FILE(APPEND ${asset_asm} ".incbin \"${asset_cpio}\"\n")
endif ()
FILE(APPEND ${asset_asm} ".global ${SYM_PREFIX}clap_asset_cpio_end\n")
FILE(APPEND ${asset_asm} "${SYM_PREFIX}clap_asset_cpio_end:\n")
FILE(APPEND ${asset_asm} ".byte 0\n")
