# Use -DCLAP_RENDERER to select a renderer
if (APPLE)
    set(CLAP_RENDERER "Metal" CACHE STRING "Graphics renderer")
else ()
    set(CLAP_RENDERER "OpenGL" CACHE STRING "Graphics renderer")
endif ()

if (${CLAP_RENDERER} STREQUAL "OpenGL")
    set(CONFIG_RENDERER_OPENGL 1)
elseif (${CLAP_RENDERER} STREQUAL "Metal")
    set(CONFIG_RENDERER_METAL 1)
elseif (${CLAP_RENDERER} STREQUAL "Vulkan")
    set(CONFIG_RENDERER_VULKAN 1)
    message(FATAL_ERROR "Vulkan renderer is not supported yet")
elseif (${CLAP_RENDERER} STREQUAL "D3D12")
    set(CONFIG_RENDERER_D3D12 1)
    message(FATAL_ERROR "D3D12 renderer is not supported yet")
else ()
    message(FATAL_ERROR "Unsupported renderer: ${CLAP_RENDERER}")
endif ()

if ((${CMAKE_SYSTEM_NAME} MATCHES "Emscripten") AND NOT CONFIG_RENDERER_OPENGL)
    message(FATAL_ERROR "Emscripten build only supports OpenGL renderer")
endif ()

message(STATUS "Rendering backend: ${CLAP_RENDERER}")
