# Use -DCLAP_RENDERER to select a renderer
if (APPLE)
    set(CLAP_RENDERER "Metal" CACHE STRING "Graphics renderer")
else ()
    set(CLAP_RENDERER "OpenGL" CACHE STRING "Graphics renderer")
endif ()

foreach(renderer ${CLAP_RENDERER})
    if (${renderer} STREQUAL "OpenGL")
        set(CONFIG_RENDERER_OPENGL 1)
    elseif (${renderer} STREQUAL "Metal")
        set(CONFIG_RENDERER_METAL 1)
    elseif (${renderer} STREQUAL "WebGPU")
        set(CONFIG_RENDERER_WGPU 1)
    elseif (${renderer} STREQUAL "Vulkan")
        set(CONFIG_RENDERER_VULKAN 1)
        message(FATAL_ERROR "Vulkan renderer is not supported yet")
    elseif (${renderer} STREQUAL "D3D12")
        set(CONFIG_RENDERER_D3D12 1)
        message(FATAL_ERROR "D3D12 renderer is not supported yet")
    else ()
        message(FATAL_ERROR "Unsupported renderer: ${renderer}")
    endif ()
    message(STATUS "Rendering backend: ${renderer}")
endforeach()

if ((${CMAKE_SYSTEM_NAME} MATCHES "Emscripten") AND NOT (CONFIG_RENDERER_OPENGL OR CONFIG_RENDERER_WGPU))
    message(FATAL_ERROR "Emscripten build only supports OpenGL and WebGPU renderers")
endif ()
