name: simple-build
on: [push]
jobs:
  build-ubuntu:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: submodules
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive --depth 1
          git clone --depth 1 https://github.com/emscripten-core/emsdk.git
          cd emsdk && ./emsdk install latest && ./emsdk activate latest
      - name: install-deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libfreetype-dev libglew-dev libglfw3-dev libogg-dev libopenal-dev libpng-dev libvorbis-dev zlib1g-dev glslc spirv-cross
      - name: configure
        run: |
          cd ${{ github.workspace }}
          touch build_config
          echo emsdk_env_path=\"${{ github.workspace }}/emsdk/emsdk_env.sh\" >> build_config
          echo opts=\"--parallel 4\" >> build_config
          echo www_dir=\"${{ github.workspace }}/www/${GITHUB_REF##*/}\" >> build_config
          ./configure.sh
      - name: build
        run: |
          cd ${{ github.workspace }}
          ./build.sh
          git config --global --unset url."https://github.com/".insteadOf
          export branch=""
      - name: upload-clap
        uses: actions/upload-artifact@v4
        with:
          name: clap
          retention-days: 30
          path: ${{ github.workspace }}/www/${GITHUB_REF##*/}/clap
      - name: upload-claptest
        uses: actions/upload-artifact@v4
        with:
          name: claptest
          retention-days: 30
          path: ${{ github.workspace }}/www/${GITHUB_REF##*/}/claptest
      - name: upload-clapdbg
        uses: actions/upload-artifact@v4
        with:
          name: clapdbg
          retention-days: 30
          path: ${{ github.workspace }}/www/${GITHUB_REF##*/}/clapdbg
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
            SSH_PRIVATE_KEY: ${{ secrets.REMOTE_DEPLOY_KEY }}
            ARGS: "-rlgoDzvc -i"
            SOURCE: "www/"
            REMOTE_HOST: ${{ secrets.REMOTE_DEPLOY_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_DEPLOY_USER }}
            TARGET: ${{ secrets.REMOTE_DEPLOY_TARGET }}
      # - name: deploy
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: www
      #     ssh-key: ${{ secrets.DEPLOY_KEY }}
      #     branch: main
      #     git-config-name: Deployer
      #     git-config-email: alex@ash.works
      #     repository-name: virtuoso/virtuoso.github.io
      #     target-folder: clap
      #     clean: false
