name: windows-build
on: [push]
jobs:
  build-windows:
    runs-on: windows-2019
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
    defaults:
      run:
        shell: bash
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: submodules
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive --depth 1
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: install-deps
        run: |
          pwd
          echo "${{ github.workspace }}"
          vcpkg install libpng:x64-windows-static glfw3:x64-windows-static glew:x64-windows-static freetype:x64-windows-static openal-soft:x64-windows-static libogg:x64-windows-static libvorbis:x64-windows-static shaderc spirv-cross
      - name: Install Ninja
        run: |
          curl -L -o ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-win.zip
          mkdir ~/bin
          unzip ninja.zip -d ~/bin
          echo "${HOME}/bin" >> $GITHUB_PATH
      - name: configure
        run: |
          cmake --preset w32test -B build/test "${{ github.workspace }}"
          cmake --preset w32debug -B build/debug "${{ github.workspace }}"
      - name: build
        run: |
          cmake --build build/test --parallel 4
          cmake --build build/debug --parallel 4
      - name: test
        run: |
          ctest --test-dir build/debug
      - name: upload-artifact-w32test
        uses: actions/upload-artifact@v4
        with:
          name: clap
          retention-days: 30
          path: ${{ github.workspace }}/build/test/demo/ldjam56/ldjam56.exe
      - name: upload-artifact-w32debug
        uses: actions/upload-artifact@v4
        with:
          name: clapdbg
          retention-days: 30
          path: ${{ github.workspace }}/build/debug/demo/ldjam56/ldjam56.exe
